### ISSUE TITLE
AWS bitnami deploy of Django app: OperationalError attempt to write a readonly database

### ISSUE THREAD

**Issue by mchesler613** [mbi/django-simple-captcha#198]
Hi, I am trying to deploy my simple app that uses your wonderful package, `django-simple-captcha` on AWS. 

I am running into a problem of this:
```
OperationalError: attempt to write a readonly database
```

Here is the traceback:
```
Environment:


Request Method: GET
Request URL: http://18.215.172.242/djangomail/contact/

Django Version: 3.1.6
Python Version: 3.8.7
Installed Applications:
['captcha',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']


Template error:
In template /opt/bitnami/projects/djangomail/djangomail/templates/base.html, error at line 8
   attempt to write a readonly database
   1 : <!DOCTYPE HTML>
   2 : <html>
   3 :   <head>
   4 :     <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
   5 :   </head>
   6 : 
   7 :   <body>
   8 :     <div class="w3-mobile w3-container w3-margin w 3-padding" >
   9 :     {% if messages %}
   10 :       <ul class="w3-ul w3-light-blue">
   11 :       {% for message in messages %}
   12 :         <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
   13 :       {% endfor %}
   14 :       </ul>
   15 :     {% endif %}
   16 : 
   17 :     {% block content %}
   18 :     {% endblock content %}


Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)

The above exception (attempt to write a readonly database) was the direct cause of the following exception:
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/template/base.py", line 994, in render
    return render_value_in_context(output, context)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/template/base.py", line 973, in render_value_in_context
    value = str(value)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/utils/html.py", line 376, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/forms/forms.py", line 134, in __str__
    return self.as_table()
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/forms/forms.py", line 272, in as_table
    return self._html_output(
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/forms/forms.py", line 229, in _html_output
    output.append(normal_row % {
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/utils/html.py", line 376, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/forms/boundfield.py", line 34, in __str__
    return self.as_widget()
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/forms/boundfield.py", line 93, in as_widget
    return widget.render(
  File "/opt/bitnami/python/lib/python3.8/site-packages/captcha/fields.py", line 198, in render
    self.fetch_captcha_store(name, value, attrs, self.generator)
  File "/opt/bitnami/python/lib/python3.8/site-packages/captcha/fields.py", line 68, in fetch_captcha_store
    key = CaptchaStore.generate_key(generator)
  File "/opt/bitnami/python/lib/python3.8/site-packages/captcha/models.py", line 67, in generate_key
    store = cls.objects.create(challenge=challenge, response=response)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/bitnami/python/lib/python3.8/site-packages/captcha/models.py", line 54, in save
    super(CaptchaStore, self).save(*args, **kwargs)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/db/models/base.py", line 790, in save_base
    updated = self._save_table(
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/db/models/base.py", line 933, in _do_insert
    return manager._insert(
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/bitnami/python/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)

Exception Type: OperationalError at /contact/
Exception Value: attempt to write a readonly database

```

Can you please direct me to how to fix this permissions problem?  I installed `sudo pip install django-simple-captcha`, ran `sudo /opt/bitnami/ctlscript.sh restart apache` and even changed read-write permissions of `db.sqlite3` to root.  

Thank you in advance for all your help.

**Comment by mbi** [comment]
Hi. This is completely unrelated to Django Simple Captcha, but a deployment / configuration issue with your project. Sorry, no idea what is wrong.

**Comment by mchesler613** [comment]
Thank you for looking into the matter. For those who are experiencing the some problem, I found a resolution here, https://community.bitnami.com/t/django-and-apache-operationalerror-attempt-to-write-a-readonly-database/84425/5. :)
