### ISSUE TITLE
Import Error. No module named Image

### ISSUE THREAD

**Issue by jl2035** [mbi/django-simple-captcha#89]
I have found many questions on stackoverflow about this, but I guess I'm not smart enough to help myself with any of the solutions they provide. I have followed this documentation http://django-simple-captcha.readthedocs.org/en/latest/usage.html very precisely, but I must be just unlucky.

After adding this:

    urlpatterns += patterns('',
        url(r'^captcha/', include('captcha.urls')),
    )

to urls.py I'm getting this: ImportError at / No module named Image

I have no idea what's going on. The stack trace does not tell me much :)

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  98.                 resolver_match = resolver.resolve(request.path_info)
File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py" in resolve
  343.             for pattern in self.url_patterns:
File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py" in url_patterns
  372.         patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py" in urlconf_module
  366.             self._urlconf_module = import_module(self.urlconf_name)
File "/usr/lib/python2.7/importlib/__init__.py" in import_module
  37.     __import__(name)
File "/home/wuser/mysite/mysite/urls.py" in <module>
  18.    url(r'^captcha/', include('captcha.urls')),
File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py" in include
  28.         urlconf_module = import_module(urlconf_module)
File "/usr/lib/python2.7/importlib/__init__.py" in import_module
  37.     __import__(name)
File "/usr/local/lib/python2.7/dist-packages/captcha/urls.py" in <module>
  6. from captcha import views
File "/usr/local/lib/python2.7/dist-packages/captcha/views.py" in <module>
  21.     import Image

Exception Type: ImportError at /
Exception Value: No module named Image

**Comment by mbi** [comment]
did you `pip install Pillow`?

**Comment by jl2035** [comment]
I can't! This is the end of output:

x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/BoxBlur.o: No such file or directory

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-QLeVd6-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/Pillow
Storing debug log for failure in /root/.pip/pip.log

**Comment by mbi** [comment]
Uhm, if you're on Debian or Ubuntu:

`apt-get -y install libz-dev libjpeg-dev libfreetype6-dev python-dev`

Does this help? Pillow is a strict requirement, that is why you're getting the `Import Image` error

**Comment by jl2035** [comment]
whoa! Thanks for the awesomeness. This trick could be included in the docs btw...

**Comment by mbi** [comment]
Good point, will add that

**Comment by tanuka72** [comment]
"apt-get -y install libz-dev libjpeg-dev libfreetype6-dev python-dev"
What is the equivalent on CentOS?

I have Pillow 2.6.1 installed, but when I try to start Django (over Apache using mod_wsgi), I get the following traceback

[23/Dec/2015 14:54:14] ERROR [django.request:231] Internal Server Error: /
Traceback (most recent call last):
  File "/home/syt_admin/.virtualenvs/vishwaas_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/syt_admin/.virtualenvs/vishwaas_env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "/home/syt_admin/.virtualenvs/vishwaas_env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/syt_admin/.virtualenvs/vishwaas_env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/syt_admin/projects/vishwaas/vishwaas_django/vishwaas_django/urls.py", line 27, in <module>
    url(r'^captcha/', include('captcha.urls')),
  File "/home/syt_admin/.virtualenvs/vishwaas_env/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 28, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/syt_admin/.virtualenvs/vishwaas_env/lib/python2.7/site-packages/captcha/urls.py", line 2, in <module>
    from captcha import views
  File "/home/syt_admin/.virtualenvs/vishwaas_env/lib/python2.7/site-packages/captcha/views.py", line 21, in <module>
    import Image
ImportError: No module named Image

The same code worked on Windows and I was able to see the CAPTCHA in my ModelForms.

**Comment by 249143979** [comment]
Mac OX：
run：brew install Homebrew/python/pillow
